services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - spotify-listener
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.spotify-listener.schedule: "@every 10m"
      ofelia.job-run.spotify-listener.container: "spotify-listener"

  spotify-listener:
    container_name: spotify-listener
    build: .
    depends_on:
      - postgres
    env_file:
      .env
    restart: on-failure:3
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
